image: golang:1.20-alpine

stages:
  - test

run tests:
  stage: test
  image: golang:1.21-alpine
  script:
    - go install
    - CGO_ENABLED=0 go test ./... -coverprofile=coverage-report.out
    - go tool cover -html=coverage-report.out -o coverage-report.html
    - go tool cover -func=coverage-report.out
  coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"
  only: [main]